# im-web 基础配置

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
    group:
      dev: common,common-dev
      test: common,common-test
      prod: common,common-prod
  application:
    name: im-web
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoReactiveDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoReactiveRepositoriesAutoConfiguration
  webflux:
    base-path: /api

server:
  port: 8080

im:
  data:
    mongo:
      enabled: true
