# im-access 基础配置
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
    group:
      dev: common,common-dev
      test: common,common-test
      prod: common,common-prod
  application:
    name: im-access
  main:
    web-application-type: none
  rsocket:
    server:
      transport: websocket
      port: 8882
